# for hive api
hive.api.enabled=true
hive.api.base-url=
hive.api.account=
hive.api.token=
hive.api.token-header-name=

# x402 configuration
x402.enabled=true
x402.default-pay-to=0x91493feaefc824d2b4630c21d40e3647fa4b6d07
x402.network=base-sepolia
x402.asset=0x036CbD53842c5426634e7929541eC2318f3dCF7e
x402.max-timeout-seconds=30
x402.facilitator-base-url=https://www.x402.org/facilitator

# knife4j config
knife4j.enable=true
knife4j.setting.language=en

# management endpoints
management.endpoints.enabled-by-default=true
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info,prometheus

#cors
app.cors.origins=
app.cors.methods=
app.cors.headers=
app.cors.credentials=true
app.cors.max-age=